version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8088:80"
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html/
      - .docker/logs/nginx:/var/log/nginx/
  
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php8-X
    networks:
      - internal
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: 
        client_host=host.docker.internal \
        client_port=9003 \
        start_with_request=yes \
        discover_client_host=0
    volumes:
      - ./src/:/var/www/html

networks:
  internal:
    driver: bridge

    