version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/prd/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: .docker/php/prd/Dockerfile
    networks:
      - internal
networks:
  internal:
    driver: bridge