version: '3'
services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80 # Troque a porta caso seja necessário
    volumes:
      - .:/var/www/html
    links:
      - db

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: php-db
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: supauser

  phpqa:
      image: jakzal/phpqa:php7.1-alpine