version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8088:80"
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html/
      - .docker/logs/nginx:/var/log/nginx/
  
  php:
    image: php:fpm-alpine
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./src/:/var/www/html

networks:
  internal:
    driver: bridge

    